
"""
Django settings for purbeurre_project project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from dotenv import load_dotenv, find_dotenv
<<<<<<< HEAD:purbeurre_project/settings.py
from django.core.management.utils import get_random_secret_key
=======
>>>>>>> cd526d35d1bb080a5e8b8150ebc61fd1a1f6d8be:purbeurre_project/settings/__init__.py
import os
from pathlib import Path
import environ

load_dotenv(find_dotenv())
<<<<<<< HEAD:purbeurre_project/settings.py
#env_path = Path('.')/'.env'
#load_dotenv(dotenv_path=env_path)

#env = environ.Env()
#environ.Env.read_env()

=======
>>>>>>> cd526d35d1bb080a5e8b8150ebc61fd1a1f6d8be:purbeurre_project/settings/__init__.py
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD:purbeurre_project/settings.py
SECRET_KEY = os.getenv("SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('ENV', 'DEVELOPMENT') == 'PRODUCTION':
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ['134.122.106.30','127.0.0.1','localhost']
=======
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['134.122.106.30']

>>>>>>> cd526d35d1bb080a5e8b8150ebc61fd1a1f6d8be:purbeurre_project/settings/__init__.py

# Application definition

INSTALLED_APPS = [
    'catalogue.apps.CatalogueConfig',
    'user.apps.UserConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'purbeurre_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'purbeurre_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'purbeurre',
<<<<<<< HEAD:purbeurre_project/settings.py
        'USER': os.getenv('DATABASE_USER', default=""),
        'PASSWORD': os.getenv('DATABASE_PWD', default=""),
        'HOST': 'localhost',
        'PORT': '',
=======
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PWD'),
        'HOST': '',
        'PORT': '5432',
>>>>>>> cd526d35d1bb080a5e8b8150ebc61fd1a1f6d8be:purbeurre_project/settings/__init__.py
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    str(BASE_DIR / 'static'),
]
STATIC_ROOT = str(BASE_DIR / 'staticfiles')

INTERNAL_IPS = ['127.0.0.1']
<<<<<<< HEAD:purbeurre_project/settings.py

=======
>>>>>>> cd526d35d1bb080a5e8b8150ebc61fd1a1f6d8be:purbeurre_project/settings/__init__.py
