language: python

python:
  - "3.8"

addons:
  # install browsers
  firefox: latest

install:
  # installation geckodriver
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz -P ~/
  # unzip and clean up
  - tar -xzf ~/geckodriver-v0.29.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.0-linux64.tar.gz
  # make driver accessible
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
